<template>
    <div>
        <div class="home js-ajax" style=" max-width:1200px;" ><div class="box gray no-padding has-subtitle" id="js-category_product_carousel_1" style="margin-left: 450px;">
            <div class="box-heading padding">
                <div class="ribbon-container">
                    <div class="ribbon-text">Dünya Dilleri</div>
                </div>
                <div class="heading-nav-horizontal">
                    <a class="view-all" href="https://www.kitapyurdu.com/index.php?route=product/category&amp;sort=purchased&amp;order=DESC&amp;path=437&amp;filter_in_stock=1" data-title="İngilizce" style="margin-left: 450px;">Tümünü Göster</a>
                    <div class="heading-nav-arrows"><a class="common-sprite prev swiper-button-disabled" tabindex="0" role="button" aria-label="Previous slide" aria-disabled="true"></a><a class="common-sprite next" tabindex="0" role="button" aria-label="Next slide" aria-disabled="false"></a></div>
                </div>
        
                <div class="js-heading-links">
                    <a class="sub-title-638 selected">İngilizce</a>
                    <a class="sub-title-639">Almanca</a>
                    <a class="sub-title-732">Rusça</a>
                    <a class="sub-title-731">Osmanlıca</a>
                    <a class="sub-title-733">Arapça</a>
                    <a class="sub-title-734">Fransızca</a>
                </div>
            </div>
        
            <div class="box-content product-grid-wr"><div class="swiper-container swiper-container-initialized swiper-container-horizontal" style="cursor: grab;">
            <ul class="product-grid swiper-wrapper" style="display: flex; width: 100%; transition-duration: 0ms; transform: translate3d(2px, 0px, 0px);">
                    <li class="swiper-slide swiper-slide-active"><div class="product-cr" id="product-399723"><a class="pr-img-link" href="https://www.kitapyurdu.com/kitap/ingilizce-bulmacalarla-kahve-molasi-1/399723.html"><img src="https://img.kitapyurdu.com/v1/getImage/fn:2885419/wi:120/wh:true" alt="İngilizce Bulmacalarla Kahve Molası -1"></a><a class="name" href="https://www.kitapyurdu.com/kitap/ingilizce-bulmacalarla-kahve-molasi-1/399723.html" title="İngilizce Bulmacalarla Kahve Molası -1"><span class=" line-clamp-2">İngilizce Bulmacalarla Kahve Molası -1</span></a><div class="price"><div class="price-new "><span class="value"><span class="TL"></span> 19,50</span></div></div><div class="hover-menu-home"><a class="add-to-cart-home" onclick="addToCart(399723);" data-title="Sepete Ekle"><i class="fa fa-shopping-cart"></i></a><a onclick="showAjaxBox('https://www.kitapyurdu.com/index.php?route=product/product/page_image&amp;product_id=399723', true)" data-title="İç Sayfalar"><i class="fa fa-book"></i></a><a class="in-favorites-home" style="display:none;" onclick="removeFromFavorites(399723);" data-title="Favorilerinizde"><i class="fa fa-heart red"></i></a><a class="add-to-favorites-home" onclick="addToFavorites(399723);" data-title="Favorilerime Ekle"><i class="fa fa-heart"></i></a><a id="product-wish-list-remove-399723" onclick="removeFromWishList(399723);" data-title="Alışveriş Listemden Çıkar" style="color: #FF8000; display: none"><i class="fa fa-tag"></i></a><a id="product-wish-list-add-399723" onclick="addToWishList(399723);" data-title="Alışveriş Listeme Ekle" style="display: inline-block"><i class="fa fa-tag"></i></a></div><div class="notice-container"><div class="notice-home same-day purple"><i class="fa fa-plane"></i>&nbsp;<span class="text">24 Saatte Kargoda</span></div></div></div></li>
                    <li class="swiper-slide swiper-slide-next"><div class="product-cr" id="product-567995"><a class="pr-img-link" href="https://www.kitapyurdu.com/kitap/nineteen-eightyfour-1984/567995.html"><img src="https://img.kitapyurdu.com/v1/getImage/fn:11340163/wi:120/wh:true" alt="Nineteen Eighty-Four - 1984"></a><a class="name" href="https://www.kitapyurdu.com/kitap/nineteen-eightyfour-1984/567995.html" title="Nineteen Eighty-Four - 1984"><span class=" line-clamp-2">Nineteen Eighty-Four - 1984</span></a><div class="price"><div class="price-new "><span class="value"><span class="TL"></span> 33,80</span></div></div><div class="hover-menu-home"><a class="add-to-cart-home" onclick="addToCart(567995);" data-title="Sepete Ekle"><i class="fa fa-shopping-cart"></i></a><a class="in-favorites-home" style="display:none;" onclick="removeFromFavorites(567995);" data-title="Favorilerinizde"><i class="fa fa-heart red"></i></a><a class="add-to-favorites-home" onclick="addToFavorites(567995);" data-title="Favorilerime Ekle"><i class="fa fa-heart"></i></a><a id="product-wish-list-remove-567995" onclick="removeFromWishList(567995);" data-title="Alışveriş Listemden Çıkar" style="color: #FF8000; display: none"><i class="fa fa-tag"></i></a><a id="product-wish-list-add-567995" onclick="addToWishList(567995);" data-title="Alışveriş Listeme Ekle" style="display: inline-block"><i class="fa fa-tag"></i></a></div><div class="notice-container"><div class="notice-home same-day purple"><i class="fa fa-plane"></i>&nbsp;<span class="text">24 Saatte Kargoda</span></div></div></div></li>
                    <li class="swiper-slide"><div class="product-cr" id="product-429188"><a class="pr-img-link" href="https://www.kitapyurdu.com/kitap/fahrenheit-451/429188.html"><img src="https://img.kitapyurdu.com/v1/getImage/fn:7150718/wi:120/wh:true" alt="Fahrenheit 451"></a><a class="name" href="https://www.kitapyurdu.com/kitap/fahrenheit-451/429188.html" title="Fahrenheit 451"><span class=" line-clamp-2">Fahrenheit 451</span></a><div class="price"><div class="price-new "><span class="value"><span class="TL"></span> 160,55</span></div></div><div class="hover-menu-home"><a class="add-to-cart-home" onclick="addToCart(429188);" data-title="Sepete Ekle"><i class="fa fa-shopping-cart"></i></a><a onclick="showAjaxBox('https://www.kitapyurdu.com/index.php?route=product/product/page_image&amp;product_id=429188', true)" data-title="İç Sayfalar"><i class="fa fa-book"></i></a><a class="in-favorites-home" style="display:none;" onclick="removeFromFavorites(429188);" data-title="Favorilerinizde"><i class="fa fa-heart red"></i></a><a class="add-to-favorites-home" onclick="addToFavorites(429188);" data-title="Favorilerime Ekle"><i class="fa fa-heart"></i></a><a id="product-wish-list-remove-429188" onclick="removeFromWishList(429188);" data-title="Alışveriş Listemden Çıkar" style="color: #FF8000; display: none"><i class="fa fa-tag"></i></a><a id="product-wish-list-add-429188" onclick="addToWishList(429188);" data-title="Alışveriş Listeme Ekle" style="display: inline-block"><i class="fa fa-tag"></i></a></div><div class="notice-container"><div class="notice-home free-shipping-same-day purple"><i class="fa fa-plane"></i>&nbsp;<div class="text">Kargo Bedava<br>24 Saatte Kargoda</div></div></div></div></li>
                    <li class="swiper-slide"><div class="product-cr" id="product-388147"><a class="pr-img-link" href="https://www.kitapyurdu.com/kitap/the-little-prince/388147.html"><img src="https://img.kitapyurdu.com/v1/getImage/fn:1152568/wi:120/wh:true" alt="The Little Prince"></a><a class="name" href="https://www.kitapyurdu.com/kitap/the-little-prince/388147.html" title="The Little Prince"><span class=" line-clamp-2">The Little Prince</span></a><div class="price"><div class="price-new "><span class="value"><span class="TL"></span> 23,40</span></div></div><div class="hover-menu-home"><a class="add-to-cart-home" onclick="addToCart(388147);" data-title="Sepete Ekle"><i class="fa fa-shopping-cart"></i></a><a onclick="showAjaxBox('https://www.kitapyurdu.com/index.php?route=product/product/page_image&amp;product_id=388147', true)" data-title="İç Sayfalar"><i class="fa fa-book"></i></a><a class="in-favorites-home" style="display:none;" onclick="removeFromFavorites(388147);" data-title="Favorilerinizde"><i class="fa fa-heart red"></i></a><a class="add-to-favorites-home" onclick="addToFavorites(388147);" data-title="Favorilerime Ekle"><i class="fa fa-heart"></i></a><a id="product-wish-list-remove-388147" onclick="removeFromWishList(388147);" data-title="Alışveriş Listemden Çıkar" style="color: #FF8000; display: none"><i class="fa fa-tag"></i></a><a id="product-wish-list-add-388147" onclick="addToWishList(388147);" data-title="Alışveriş Listeme Ekle" style="display: inline-block"><i class="fa fa-tag"></i></a></div><div class="notice-container"><div class="notice-home same-day purple"><i class="fa fa-plane"></i>&nbsp;<span class="text">24 Saatte Kargoda</span></div></div></div></li>
                    
                    
                </ul>
            <div class="swiper-scrollbar" style="opacity: 0; transition-duration: 400ms;"><div class="swiper-scrollbar-drag" style="transform: translate3d(0px, 0px, 0px); transition-duration: 0ms; width: 249.182px;"></div></div>
        <span class="swiper-notification" aria-live="assertive" aria-atomic="true"></span></div>
        </div>
        </div>
        </div>
        <div>
            <div class="home js-lazy"><div class="ad-large" id="ad-24" style="margin-left: 450px;"><a href="index.php?route=ad/redirect&amp;ad_id=253" target="_self" rel="nofollow"><img class="img-lazy-loaded" data-src="https://img.kitapyurdu.com/v1/getImage/fn:11571860/wh:fdc816c61" alt="banner" src="https://img.kitapyurdu.com/v1/getImage/fn:11571860/wh:fdc816c61" width="10000" height="100"></a></div></div>
        </div>
    </div>
</template>