<template>
    <div>
        <div class="home js-ajax"><div class="box gray no-padding has-subtitle" id="js-category_product_carousel_1">
            <div class="box-heading padding">
                <div class="ribbon-container">
                    <div class="ribbon-text">Dünya Dilleri</div>
                </div>
                <div class="heading-nav-horizontal">
                    <a class="view-all" href="https://www.kitapyurdu.com/index.php?route=product/category&amp;sort=purchased&amp;order=DESC&amp;path=437&amp;filter_in_stock=1" data-title="İngilizce">Tümünü Göster</a>
                    <div class="heading-nav-arrows"><a class="common-sprite prev swiper-button-disabled" tabindex="0" role="button" aria-label="Previous slide" aria-disabled="true"></a><a class="common-sprite next" tabindex="0" role="button" aria-label="Next slide" aria-disabled="false"></a></div>
                </div>
        
                <div class="js-heading-links">
                    <a class="sub-title-638 selected">İngilizce</a>
                    <a class="sub-title-639">Almanca</a>
                    <a class="sub-title-732">Rusça</a>
                    <a class="sub-title-731">Osmanlıca</a>
                    <a class="sub-title-733">Arapça</a>
                    <a class="sub-title-734">Fransızca</a>
                </div>
            </div>
        
            <div class="box-content product-grid-wr"><div class="swiper-container swiper-container-initialized swiper-container-horizontal" style="cursor: grab;">
            <ul class="product-grid swiper-wrapper" style="display: flex; width: 100%; transition-duration: 0ms; transform: translate3d(2px, 0px, 0px);">
                    <li class="swiper-slide swiper-slide-active"><div class="product-cr" id="product-399723"><a class="pr-img-link" href="https://www.kitapyurdu.com/kitap/ingilizce-bulmacalarla-kahve-molasi-1/399723.html"><img src="https://img.kitapyurdu.com/v1/getImage/fn:2885419/wi:120/wh:true" alt="İngilizce Bulmacalarla Kahve Molası -1"></a><a class="name" href="https://www.kitapyurdu.com/kitap/ingilizce-bulmacalarla-kahve-molasi-1/399723.html" title="İngilizce Bulmacalarla Kahve Molası -1"><span class=" line-clamp-2">İngilizce Bulmacalarla Kahve Molası -1</span></a><div class="price"><div class="price-new "><span class="value"><span class="TL"></span> 19,50</span></div></div><div class="hover-menu-home"><a class="add-to-cart-home" onclick="addToCart(399723);" data-title="Sepete Ekle"><i class="fa fa-shopping-cart"></i></a><a onclick="showAjaxBox('https://www.kitapyurdu.com/index.php?route=product/product/page_image&amp;product_id=399723', true)" data-title="İç Sayfalar"><i class="fa fa-book"></i></a><a class="in-favorites-home" style="display:none;" onclick="removeFromFavorites(399723);" data-title="Favorilerinizde"><i class="fa fa-heart red"></i></a><a class="add-to-favorites-home" onclick="addToFavorites(399723);" data-title="Favorilerime Ekle"><i class="fa fa-heart"></i></a><a id="product-wish-list-remove-399723" onclick="removeFromWishList(399723);" data-title="Alışveriş Listemden Çıkar" style="color: #FF8000; display: none"><i class="fa fa-tag"></i></a><a id="product-wish-list-add-399723" onclick="addToWishList(399723);" data-title="Alışveriş Listeme Ekle" style="display: inline-block"><i class="fa fa-tag"></i></a></div><div class="notice-container"><div class="notice-home same-day purple"><i class="fa fa-plane"></i>&nbsp;<span class="text">24 Saatte Kargoda</span></div></div></div></li>
                    <li class="swiper-slide swiper-slide-next"><div class="product-cr" id="product-567995"><a class="pr-img-link" href="https://www.kitapyurdu.com/kitap/nineteen-eightyfour-1984/567995.html"><img src="https://img.kitapyurdu.com/v1/getImage/fn:11340163/wi:120/wh:true" alt="Nineteen Eighty-Four - 1984"></a><a class="name" href="https://www.kitapyurdu.com/kitap/nineteen-eightyfour-1984/567995.html" title="Nineteen Eighty-Four - 1984"><span class=" line-clamp-2">Nineteen Eighty-Four - 1984</span></a><div class="price"><div class="price-new "><span class="value"><span class="TL"></span> 33,80</span></div></div><div class="hover-menu-home"><a class="add-to-cart-home" onclick="addToCart(567995);" data-title="Sepete Ekle"><i class="fa fa-shopping-cart"></i></a><a class="in-favorites-home" style="display:none;" onclick="removeFromFavorites(567995);" data-title="Favorilerinizde"><i class="fa fa-heart red"></i></a><a class="add-to-favorites-home" onclick="addToFavorites(567995);" data-title="Favorilerime Ekle"><i class="fa fa-heart"></i></a><a id="product-wish-list-remove-567995" onclick="removeFromWishList(567995);" data-title="Alışveriş Listemden Çıkar" style="color: #FF8000; display: none"><i class="fa fa-tag"></i></a><a id="product-wish-list-add-567995" onclick="addToWishList(567995);" data-title="Alışveriş Listeme Ekle" style="display: inline-block"><i class="fa fa-tag"></i></a></div><div class="notice-container"><div class="notice-home same-day purple"><i class="fa fa-plane"></i>&nbsp;<span class="text">24 Saatte Kargoda</span></div></div></div></li>
                    <li class="swiper-slide"><div class="product-cr" id="product-429188"><a class="pr-img-link" href="https://www.kitapyurdu.com/kitap/fahrenheit-451/429188.html"><img src="https://img.kitapyurdu.com/v1/getImage/fn:7150718/wi:120/wh:true" alt="Fahrenheit 451"></a><a class="name" href="https://www.kitapyurdu.com/kitap/fahrenheit-451/429188.html" title="Fahrenheit 451"><span class=" line-clamp-2">Fahrenheit 451</span></a><div class="price"><div class="price-new "><span class="value"><span class="TL"></span> 160,55</span></div></div><div class="hover-menu-home"><a class="add-to-cart-home" onclick="addToCart(429188);" data-title="Sepete Ekle"><i class="fa fa-shopping-cart"></i></a><a onclick="showAjaxBox('https://www.kitapyurdu.com/index.php?route=product/product/page_image&amp;product_id=429188', true)" data-title="İç Sayfalar"><i class="fa fa-book"></i></a><a class="in-favorites-home" style="display:none;" onclick="removeFromFavorites(429188);" data-title="Favorilerinizde"><i class="fa fa-heart red"></i></a><a class="add-to-favorites-home" onclick="addToFavorites(429188);" data-title="Favorilerime Ekle"><i class="fa fa-heart"></i></a><a id="product-wish-list-remove-429188" onclick="removeFromWishList(429188);" data-title="Alışveriş Listemden Çıkar" style="color: #FF8000; display: none"><i class="fa fa-tag"></i></a><a id="product-wish-list-add-429188" onclick="addToWishList(429188);" data-title="Alışveriş Listeme Ekle" style="display: inline-block"><i class="fa fa-tag"></i></a></div><div class="notice-container"><div class="notice-home free-shipping-same-day purple"><i class="fa fa-plane"></i>&nbsp;<div class="text">Kargo Bedava<br>24 Saatte Kargoda</div></div></div></div></li>
                    <li class="swiper-slide"><div class="product-cr" id="product-388147"><a class="pr-img-link" href="https://www.kitapyurdu.com/kitap/the-little-prince/388147.html"><img src="https://img.kitapyurdu.com/v1/getImage/fn:1152568/wi:120/wh:true" alt="The Little Prince"></a><a class="name" href="https://www.kitapyurdu.com/kitap/the-little-prince/388147.html" title="The Little Prince"><span class=" line-clamp-2">The Little Prince</span></a><div class="price"><div class="price-new "><span class="value"><span class="TL"></span> 23,40</span></div></div><div class="hover-menu-home"><a class="add-to-cart-home" onclick="addToCart(388147);" data-title="Sepete Ekle"><i class="fa fa-shopping-cart"></i></a><a onclick="showAjaxBox('https://www.kitapyurdu.com/index.php?route=product/product/page_image&amp;product_id=388147', true)" data-title="İç Sayfalar"><i class="fa fa-book"></i></a><a class="in-favorites-home" style="display:none;" onclick="removeFromFavorites(388147);" data-title="Favorilerinizde"><i class="fa fa-heart red"></i></a><a class="add-to-favorites-home" onclick="addToFavorites(388147);" data-title="Favorilerime Ekle"><i class="fa fa-heart"></i></a><a id="product-wish-list-remove-388147" onclick="removeFromWishList(388147);" data-title="Alışveriş Listemden Çıkar" style="color: #FF8000; display: none"><i class="fa fa-tag"></i></a><a id="product-wish-list-add-388147" onclick="addToWishList(388147);" data-title="Alışveriş Listeme Ekle" style="display: inline-block"><i class="fa fa-tag"></i></a></div><div class="notice-container"><div class="notice-home same-day purple"><i class="fa fa-plane"></i>&nbsp;<span class="text">24 Saatte Kargoda</span></div></div></div></li>
                    <li class="swiper-slide"><div class="product-cr" id="product-567997"><a class="pr-img-link" href="https://www.kitapyurdu.com/kitap/animal-farm/567997.html"><img src="https://img.kitapyurdu.com/v1/getImage/fn:11340168/wi:120/wh:true" alt="Animal Farm"></a><a class="name" href="https://www.kitapyurdu.com/kitap/animal-farm/567997.html" title="Animal Farm"><span class=" line-clamp-2">Animal Farm</span></a><div class="price"><div class="price-new "><span class="value"><span class="TL"></span> 19,50</span></div></div><div class="hover-menu-home"><a class="add-to-cart-home" onclick="addToCart(567997);" data-title="Sepete Ekle"><i class="fa fa-shopping-cart"></i></a><a onclick="showAjaxBox('https://www.kitapyurdu.com/index.php?route=product/product/page_image&amp;product_id=567997', true)" data-title="İç Sayfalar"><i class="fa fa-book"></i></a><a class="in-favorites-home" style="display:none;" onclick="removeFromFavorites(567997);" data-title="Favorilerinizde"><i class="fa fa-heart red"></i></a><a class="add-to-favorites-home" onclick="addToFavorites(567997);" data-title="Favorilerime Ekle"><i class="fa fa-heart"></i></a><a id="product-wish-list-remove-567997" onclick="removeFromWishList(567997);" data-title="Alışveriş Listemden Çıkar" style="color: #FF8000; display: none"><i class="fa fa-tag"></i></a><a id="product-wish-list-add-567997" onclick="addToWishList(567997);" data-title="Alışveriş Listeme Ekle" style="display: inline-block"><i class="fa fa-tag"></i></a></div><div class="notice-container"><div class="notice-home same-day purple"><i class="fa fa-plane"></i>&nbsp;<span class="text">24 Saatte Kargoda</span></div></div></div></li>
                    <li class="swiper-slide"><div class="product-cr" id="product-629313"><a class="pr-img-link" href="https://www.kitapyurdu.com/kitap/discovering-the-ottomans-karton-kapak/629313.html"><img class="swiper-lazy" data-src="https://img.kitapyurdu.com/v1/getImage/fn:11618443/wi:120/wh:true" alt="Discovering The Ottomans (Karton Kapak)"></a><a class="name" href="https://www.kitapyurdu.com/kitap/discovering-the-ottomans-karton-kapak/629313.html" title="Discovering The Ottomans (Karton Kapak)"><span class=" line-clamp-2">Discovering The Ottomans (Karton Kapak)</span></a><div class="price"><div class="price-new "><span class="value"><span class="TL"></span> 59,40</span></div></div><div class="hover-menu-home"><a class="add-to-cart-home" onclick="addToCart(629313);" data-title="Sepete Ekle"><i class="fa fa-shopping-cart"></i></a><a class="in-favorites-home" style="display:none;" onclick="removeFromFavorites(629313);" data-title="Favorilerinizde"><i class="fa fa-heart red"></i></a><a class="add-to-favorites-home" onclick="addToFavorites(629313);" data-title="Favorilerime Ekle"><i class="fa fa-heart"></i></a><a id="product-wish-list-remove-629313" onclick="removeFromWishList(629313);" data-title="Alışveriş Listemden Çıkar" style="color: #FF8000; display: none"><i class="fa fa-tag"></i></a><a id="product-wish-list-add-629313" onclick="addToWishList(629313);" data-title="Alışveriş Listeme Ekle" style="display: inline-block"><i class="fa fa-tag"></i></a></div><div class="notice-container"><div class="notice-home same-day purple"><i class="fa fa-plane"></i>&nbsp;<span class="text">24 Saatte Kargoda</span></div></div></div></li>
                    <li class="swiper-slide"><div class="product-cr" id="product-516812"><a class="pr-img-link" href="https://www.kitapyurdu.com/kitap/the-last-prophet-muhammad-4-cilt/516812.html"><img class="swiper-lazy" data-src="https://img.kitapyurdu.com/v1/getImage/fn:11535231/wi:120/wh:true" alt="The Last Prophet Muhammad (4 Cilt)"></a><a class="name" href="https://www.kitapyurdu.com/kitap/the-last-prophet-muhammad-4-cilt/516812.html" title="The Last Prophet Muhammad (4 Cilt)"><span class=" line-clamp-2">The Last Prophet Muhammad (4 Cilt)</span></a><div class="price"><div class="price-new "><span class="value"><span class="TL"></span> 65,70</span></div></div><div class="hover-menu-home"><a class="add-to-cart-home" onclick="addToCart(516812);" data-title="Sepete Ekle"><i class="fa fa-shopping-cart"></i></a><a class="in-favorites-home" style="display:none;" onclick="removeFromFavorites(516812);" data-title="Favorilerinizde"><i class="fa fa-heart red"></i></a><a class="add-to-favorites-home" onclick="addToFavorites(516812);" data-title="Favorilerime Ekle"><i class="fa fa-heart"></i></a><a id="product-wish-list-remove-516812" onclick="removeFromWishList(516812);" data-title="Alışveriş Listemden Çıkar" style="color: #FF8000; display: none"><i class="fa fa-tag"></i></a><a id="product-wish-list-add-516812" onclick="addToWishList(516812);" data-title="Alışveriş Listeme Ekle" style="display: inline-block"><i class="fa fa-tag"></i></a></div><div class="notice-container"><div class="notice-home same-day purple"><i class="fa fa-plane"></i>&nbsp;<span class="text">24 Saatte Kargoda</span></div></div></div></li>
                    <li class="swiper-slide"><div class="product-cr" id="product-411346"><a class="pr-img-link" href="https://www.kitapyurdu.com/kitap/the-godfather/411346.html"><img class="swiper-lazy" data-src="https://img.kitapyurdu.com/v1/getImage/fn:2707603/wi:120/wh:true" alt="The Godfather"></a><a class="name" href="https://www.kitapyurdu.com/kitap/the-godfather/411346.html" title="The Godfather"><span class=" line-clamp-2">The Godfather</span></a><div class="price"><div class="price-new "><span class="value"><span class="TL"></span> 167,84</span></div></div><div class="hover-menu-home"><a class="add-to-cart-home" onclick="addToCart(411346);" data-title="Sepete Ekle"><i class="fa fa-shopping-cart"></i></a><a onclick="showAjaxBox('https://www.kitapyurdu.com/index.php?route=product/product/page_image&amp;product_id=411346', true)" data-title="İç Sayfalar"><i class="fa fa-book"></i></a><a class="in-favorites-home" style="display:none;" onclick="removeFromFavorites(411346);" data-title="Favorilerinizde"><i class="fa fa-heart red"></i></a><a class="add-to-favorites-home" onclick="addToFavorites(411346);" data-title="Favorilerime Ekle"><i class="fa fa-heart"></i></a><a id="product-wish-list-remove-411346" onclick="removeFromWishList(411346);" data-title="Alışveriş Listemden Çıkar" style="color: #FF8000; display: none"><i class="fa fa-tag"></i></a><a id="product-wish-list-add-411346" onclick="addToWishList(411346);" data-title="Alışveriş Listeme Ekle" style="display: inline-block"><i class="fa fa-tag"></i></a></div><div class="notice-container"><div class="notice-home free-shipping-same-day purple"><i class="fa fa-plane"></i>&nbsp;<div class="text">Kargo Bedava<br>24 Saatte Kargoda</div></div></div></div></li>
                    <li class="swiper-slide"><div class="product-cr" id="product-131811"><a class="pr-img-link" href="https://www.kitapyurdu.com/kitap/chronicle-of-a-death-foretold/131811.html"><img class="swiper-lazy" data-src="https://img.kitapyurdu.com/v1/getImage/fn:1139441/wi:120/wh:true" alt="Chronicle Of a Death Foretold"></a><a class="name" href="https://www.kitapyurdu.com/kitap/chronicle-of-a-death-foretold/131811.html" title="Chronicle Of a Death Foretold"><span class=" line-clamp-2">Chronicle Of a Death Foretold</span></a><div class="price"><div class="price-new "><span class="value"><span class="TL"></span> 148,20</span></div></div><div class="hover-menu-home"><a class="add-to-cart-home" onclick="addToCart(131811);" data-title="Sepete Ekle"><i class="fa fa-shopping-cart"></i></a><a onclick="showAjaxBox('https://www.kitapyurdu.com/index.php?route=product/product/page_image&amp;product_id=131811', true)" data-title="İç Sayfalar"><i class="fa fa-book"></i></a><a class="in-favorites-home" style="display:none;" onclick="removeFromFavorites(131811);" data-title="Favorilerinizde"><i class="fa fa-heart red"></i></a><a class="add-to-favorites-home" onclick="addToFavorites(131811);" data-title="Favorilerime Ekle"><i class="fa fa-heart"></i></a><a id="product-wish-list-remove-131811" onclick="removeFromWishList(131811);" data-title="Alışveriş Listemden Çıkar" style="color: #FF8000; display: none"><i class="fa fa-tag"></i></a><a id="product-wish-list-add-131811" onclick="addToWishList(131811);" data-title="Alışveriş Listeme Ekle" style="display: inline-block"><i class="fa fa-tag"></i></a></div><div class="notice-container"><div class="notice-home free-shipping-same-day purple"><i class="fa fa-plane"></i>&nbsp;<div class="text">Kargo Bedava<br>24 Saatte Kargoda</div></div></div></div></li>
                    <li class="swiper-slide"><div class="product-cr" id="product-411512"><a class="pr-img-link" href="https://www.kitapyurdu.com/kitap/1q84/411512.html"><img class="swiper-lazy" data-src="https://img.kitapyurdu.com/v1/getImage/fn:2722002/wi:120/wh:true" alt="1Q84"></a><a class="name" href="https://www.kitapyurdu.com/kitap/1q84/411512.html" title="1Q84"><span class=" line-clamp-2">1Q84</span></a><div class="price"><div class="price-new "><span class="value"><span class="TL"></span> 307,66</span></div></div><div class="hover-menu-home"><a class="add-to-cart-home" onclick="addToCart(411512);" data-title="Sepete Ekle"><i class="fa fa-shopping-cart"></i></a><a class="in-favorites-home" style="display:none;" onclick="removeFromFavorites(411512);" data-title="Favorilerinizde"><i class="fa fa-heart red"></i></a><a class="add-to-favorites-home" onclick="addToFavorites(411512);" data-title="Favorilerime Ekle"><i class="fa fa-heart"></i></a><a id="product-wish-list-remove-411512" onclick="removeFromWishList(411512);" data-title="Alışveriş Listemden Çıkar" style="color: #FF8000; display: none"><i class="fa fa-tag"></i></a><a id="product-wish-list-add-411512" onclick="addToWishList(411512);" data-title="Alışveriş Listeme Ekle" style="display: inline-block"><i class="fa fa-tag"></i></a></div><div class="notice-container"><div class="notice-home free-shipping-same-day purple"><i class="fa fa-plane"></i>&nbsp;<div class="text">Kargo Bedava<br>24 Saatte Kargoda</div></div></div></div></li>
                    <li class="swiper-slide"><div class="product-cr" id="product-429204"><a class="pr-img-link" href="https://www.kitapyurdu.com/kitap/harry-potter-boxed-set/429204.html"><img class="swiper-lazy" data-src="https://img.kitapyurdu.com/v1/getImage/fn:4009849/wi:120/wh:true" alt="Harry Potter Boxed Set"></a><a class="name" href="https://www.kitapyurdu.com/kitap/harry-potter-boxed-set/429204.html" title="Harry Potter Boxed Set"><span class=" line-clamp-2">Harry Potter Boxed Set</span></a><div class="price"><span class="value"><span class="TL"></span> 1.342,51</span></div><div class="hover-menu-home"><a class="add-to-cart-home" onclick="addToCart(429204);" data-title="Sepete Ekle"><i class="fa fa-shopping-cart"></i></a><a class="in-favorites-home" style="display:none;" onclick="removeFromFavorites(429204);" data-title="Favorilerinizde"><i class="fa fa-heart red"></i></a><a class="add-to-favorites-home" onclick="addToFavorites(429204);" data-title="Favorilerime Ekle"><i class="fa fa-heart"></i></a><a id="product-wish-list-remove-429204" onclick="removeFromWishList(429204);" data-title="Alışveriş Listemden Çıkar" style="color: #FF8000; display: none"><i class="fa fa-tag"></i></a><a id="product-wish-list-add-429204" onclick="addToWishList(429204);" data-title="Alışveriş Listeme Ekle" style="display: inline-block"><i class="fa fa-tag"></i></a></div><div class="notice-container"><div class="notice-home free-shipping-same-day purple"><i class="fa fa-plane"></i>&nbsp;<div class="text">Kargo Bedava<br>24 Saatte Kargoda</div></div></div></div></li>
                    <li class="swiper-slide"><div class="product-cr" id="product-411590"><a class="pr-img-link" href="https://www.kitapyurdu.com/kitap/a-farewell-to-arms/411590.html"><img class="swiper-lazy" data-src="https://img.kitapyurdu.com/v1/getImage/fn:2728888/wi:120/wh:true" alt="A Farewell to Arms"></a><a class="name" href="https://www.kitapyurdu.com/kitap/a-farewell-to-arms/411590.html" title="A Farewell to Arms"><span class=" line-clamp-2">A Farewell to Arms</span></a><div class="price"><div class="price-new "><span class="value"><span class="TL"></span> 147,33</span></div></div><div class="hover-menu-home"><a class="add-to-cart-home" onclick="addToCart(411590);" data-title="Sepete Ekle"><i class="fa fa-shopping-cart"></i></a><a onclick="showAjaxBox('https://www.kitapyurdu.com/index.php?route=product/product/page_image&amp;product_id=411590', true)" data-title="İç Sayfalar"><i class="fa fa-book"></i></a><a class="in-favorites-home" style="display:none;" onclick="removeFromFavorites(411590);" data-title="Favorilerinizde"><i class="fa fa-heart red"></i></a><a class="add-to-favorites-home" onclick="addToFavorites(411590);" data-title="Favorilerime Ekle"><i class="fa fa-heart"></i></a><a id="product-wish-list-remove-411590" onclick="removeFromWishList(411590);" data-title="Alışveriş Listemden Çıkar" style="color: #FF8000; display: none"><i class="fa fa-tag"></i></a><a id="product-wish-list-add-411590" onclick="addToWishList(411590);" data-title="Alışveriş Listeme Ekle" style="display: inline-block"><i class="fa fa-tag"></i></a></div><div class="notice-container"><div class="notice-home free-shipping-same-day purple"><i class="fa fa-plane"></i>&nbsp;<div class="text">Kargo Bedava<br>24 Saatte Kargoda</div></div></div></div></li>
                </ul>
            <div class="swiper-scrollbar" style="opacity: 0; transition-duration: 400ms;"><div class="swiper-scrollbar-drag" style="transform: translate3d(0px, 0px, 0px); transition-duration: 0ms; width: 249.182px;"></div></div>
        <span class="swiper-notification" aria-live="assertive" aria-atomic="true"></span></div>
        </div>
        </div>
        </div>
        <div>
            <div class="home js-lazy"><div class="ad-large" id="ad-24"><a href="index.php?route=ad/redirect&amp;ad_id=253" target="_self" rel="nofollow"><img class="img-lazy-loaded" data-src="https://img.kitapyurdu.com/v1/getImage/fn:11571860/wh:fdc816c61" alt="banner" src="https://img.kitapyurdu.com/v1/getImage/fn:11571860/wh:fdc816c61" width="10000" height="100"></a></div></div>
        </div>
    </div>
</template>