<template>
    <div>
        <div class="box gray no-padding bestseller-pr-vertical" style="display: block;position: absolute; margin-left: 1350px; margin-top:-4605px; z-index: 999; padding: 0;" id="js-bestseller">
            <div class="box-heading">
                <div class="ribbon-container">
                    <div class="ribbon-text">En Çok Satılanlar</div>
                </div>
            </div>
            <div class="box-content">
                <div class="product-grid-wr"><ul class="bestseller-cr">
            <li class="bestseller-item"><a class="vertical-pr-link" href="https://www.kitapyurdu.com/kitap/gece-yarisi-kutuphanesi/582550.html"><div class="pr-img-cr"><img src="https://img.kitapyurdu.com/v1/getImage/fn:11631602/wi:50/wh:true" alt="Gece Yarısı Kütüphanesi"></div><div class="pr-details"><span class="name" title="Gece Yarısı Kütüphanesi">Gece Yarısı Kütüphanesi</span><span class="author line-clamp-2" title="Matt Haig">Matt Haig</span></div></a><span class="pr-order">1</span></li>
            <li class="bestseller-item"><a class="vertical-pr-link" href="https://www.kitapyurdu.com/kitap/ceyiz/627269.html"><div class="pr-img-cr"><img src="https://img.kitapyurdu.com/v1/getImage/fn:11607316/wi:50/wh:true" alt="Çeyiz"></div><div class="pr-details"><span class="name" title="Çeyiz">Çeyiz</span><span class="author line-clamp-2" title="Hatice Kübra Tongar">Hatice Kübra Tongar</span></div></a><span class="pr-order">2</span></li>
            <li class="bestseller-item"><a class="vertical-pr-link" href="https://www.kitapyurdu.com/kitap/bir-ask-masali/627772.html"><div class="pr-img-cr"><img src="https://img.kitapyurdu.com/v1/getImage/fn:11610438/wi:50/wh:true" alt="Bir Aşk Masalı"></div><div class="pr-details"><span class="name" title="Bir Aşk Masalı">Bir Aşk Masalı</span><span class="author line-clamp-2" title="Ahmet Ümit">Ahmet Ümit</span></div></a><span class="pr-order">3</span></li>
            <li class="bestseller-item"><a class="vertical-pr-link" href="https://www.kitapyurdu.com/kitap/uzaya-giden-tren/623243.html"><div class="pr-img-cr"><img src="https://img.kitapyurdu.com/v1/getImage/fn:11631570/wi:50/wh:true" alt="Uzaya Giden Tren"></div><div class="pr-details"><span class="name" title="Uzaya Giden Tren">Uzaya Giden Tren</span><span class="author line-clamp-2" title="Mert Arık">Mert Arık</span></div></a><span class="pr-order">4</span></li>
            <li class="bestseller-item"><a class="vertical-pr-link" href="https://www.kitapyurdu.com/kitap/var-misin-guclu-bir-yasam-icin-oneriler/568760.html"><div class="pr-img-cr"><img src="https://img.kitapyurdu.com/v1/getImage/fn:11343251/wi:50/wh:true" alt="Var Mısın? &amp; Güçlü Bir Yaşam İçin Öneriler"></div><div class="pr-details"><span class="name" title="Var Mısın? &amp; Güçlü Bir Yaşam İçin Öneriler">Var Mısın? &amp; Güçlü Bir Yaşam İçin Öneriler</span><span class="author line-clamp-2" title="Doğan Cüceloğlu">Doğan Cüceloğlu</span></div></a><span class="pr-order">5</span></li>
            <li class="bestseller-item"><a class="vertical-pr-link" href="https://www.kitapyurdu.com/kitap/seker-portakali-ciltsiz/10139.html"><div class="pr-img-cr"><img src="https://img.kitapyurdu.com/v1/getImage/fn:11462950/wi:50/wh:true" alt="Şeker Portakalı (Ciltsiz)"></div><div class="pr-details"><span class="name" title="Şeker Portakalı (Ciltsiz)">Şeker Portakalı (Ciltsiz)</span><span class="author line-clamp-2" title="Jose Mauro De Vasconcelos">Jose Mauro De Vasconcelos</span></div></a><span class="pr-order">6</span></li>
            <li class="bestseller-item"><a class="vertical-pr-link" href="https://www.kitapyurdu.com/kitap/benim-zurafam-ucabilir/589761.html"><div class="pr-img-cr"><img src="https://img.kitapyurdu.com/v1/getImage/fn:11631569/wi:50/wh:true" alt="Benim Zürafam Uçabilir"></div><div class="pr-details"><span class="name" title="Benim Zürafam Uçabilir">Benim Zürafam Uçabilir</span><span class="author line-clamp-2" title="Mert Arık">Mert Arık</span></div></a><span class="pr-order">7</span></li>
            <li class="bestseller-item"><a class="vertical-pr-link" href="https://www.kitapyurdu.com/kitap/simyaci-ciltsiz/27328.html"><div class="pr-img-cr"><img src="https://img.kitapyurdu.com/v1/getImage/fn:11582810/wi:50/wh:true" alt="Simyacı (Ciltsiz)"></div><div class="pr-details"><span class="name" title="Simyacı (Ciltsiz)">Simyacı (Ciltsiz)</span><span class="author line-clamp-2" title="Paulo Coelho">Paulo Coelho</span></div></a><span class="pr-order">8</span></li>
            <li class="bestseller-item"><a class="vertical-pr-link" href="https://www.kitapyurdu.com/kitap/insanin-anlam-arayisi/131878.html"><div class="pr-img-cr"><img src="https://img.kitapyurdu.com/v1/getImage/fn:11614703/wi:50/wh:true" alt="İnsanın Anlam Arayışı"></div><div class="pr-details"><span class="name" title="İnsanın Anlam Arayışı">İnsanın Anlam Arayışı</span><span class="author line-clamp-2" title="Viktor Emil Frankl">Viktor Emil Frankl</span></div></a><span class="pr-order">9</span></li>
            <li class="bestseller-item"><a class="vertical-pr-link" href="https://www.kitapyurdu.com/kitap/atomik-aliskanliklar/540793.html"><div class="pr-img-cr"><img src="https://img.kitapyurdu.com/v1/getImage/fn:11221036/wi:50/wh:true" alt="Atomik Alışkanlıklar"></div><div class="pr-details"><span class="name" title="Atomik Alışkanlıklar">Atomik Alışkanlıklar</span><span class="author line-clamp-2" title="James Clear">James Clear</span></div></a><span class="pr-order">10</span></li>
        </ul>
        </div>
                <div class="heading-nav-vertical padding">
                    <a class="view-all" href="https://www.kitapyurdu.com/cok-satan-kitaplar/haftalik/1.html" data-title="En Çok Satılanlar">Tümünü Göster</a>
                </div>
            </div>
        </div>
    </div>
</template>