<template>
    <div>
        <div class="home js-ajax">
            <div class="box gray featured-publisher-cr" id="js-weekly_featured_publisher_0">
            <div class="box-heading featured-publisher-heading">
                <div class="ribbon-container">
                    <div class="ribbon-text">Haftanın Yayınevi</div>
                </div>
            
                    <a class="pub-image-cr" href="https://www.kitapyurdu.com/yayinevi/altinordu-yayinlari/7791.html">
                    <img class="pub-image" src="https://img.kitapyurdu.com/v1/getImage/fn:11582373/wi:100/wh:93febe10a" alt="ALTINORDU YAYINLARI" title="ALTINORDU YAYINLARI" width="100" height="100">
                </a>
                
                <div class="pub-name line-clamp-3">
                    <span>ALTINORDU YAYINLARI</span>
                </div>
            
                    <div class="featured-publisher-discount">%45'e<br>varan indirim</div>
                
                <span class="tooltip-discount-date" data-title="14 Kasım - 21 Kasım tarihleri arasında geçerlidir."><i class="common-sprite info"></i></span>
            
                <div class="heading-nav-horizontal">
                    <a class="show-all" href="https://www.kitapyurdu.com/yayinevi/altinordu-yayinlari/7791.html">Tümünü Göster</a>
                    <div class="heading-nav-arrows"><a class="common-sprite prev swiper-button-disabled" tabindex="0" role="button" aria-label="Previous slide" aria-disabled="true"></a><a class="common-sprite next" tabindex="0" role="button" aria-label="Next slide" aria-disabled="false"></a></div>
                </div>
            
            </div>
            
            <div class="box-content product-grid-wr"><div class="swiper-container swiper-container-initialized swiper-container-horizontal" style="cursor: grab;">
                <ul class="product-grid swiper-wrapper" style="display: flex; width: 100%; transition-duration: 0ms; transform: translate3d(2px, 0px, 0px);">
                        <li class="swiper-slide swiper-slide-active"><div class="product-cr" id="product-451018"><a class="pr-img-link" href="https://www.kitapyurdu.com/kitap/teskilati-mahsusanin-reisi-suleyman-askeri-bey/451018.html"><img src="https://img.kitapyurdu.com/v1/getImage/fn:5406264/wi:120/wh:true" alt="Teşkilat-ı Mahsusa'nın Reisi Süleyman Askeri Bey"></a><a class="name" href="https://www.kitapyurdu.com/kitap/teskilati-mahsusanin-reisi-suleyman-askeri-bey/451018.html" title="Teşkilat-ı Mahsusa'nın Reisi Süleyman Askeri Bey"><span class=" line-clamp-2">Teşkilat-ı Mahsusa'nın Reisi Süleyman Askeri Bey</span></a><div class="price"><div class="price-new "><span class="value"><span class="TL"></span> 41,25</span></div></div><div class="hover-menu-home"><a class="add-to-cart-home" onclick="addToCart(451018);" data-title="Sepete Ekle"><i class="fa fa-shopping-cart"></i></a><a onclick="showAjaxBox('https://www.kitapyurdu.com/index.php?route=product/product/page_image&amp;product_id=451018', true)" data-title="İç Sayfalar"><i class="fa fa-book"></i></a><a class="in-favorites-home" style="display:none;" onclick="removeFromFavorites(451018);" data-title="Favorilerinizde"><i class="fa fa-heart red"></i></a><a class="add-to-favorites-home" onclick="addToFavorites(451018);" data-title="Favorilerime Ekle"><i class="fa fa-heart"></i></a><a id="product-wish-list-remove-451018" onclick="removeFromWishList(451018);" data-title="Alışveriş Listemden Çıkar" style="color: #FF8000; display: none"><i class="fa fa-tag"></i></a><a id="product-wish-list-add-451018" onclick="addToWishList(451018);" data-title="Alışveriş Listeme Ekle" style="display: inline-block"><i class="fa fa-tag"></i></a></div><div class="notice-container"><div class="notice-home same-day purple"><i class="fa fa-plane"></i>&nbsp;<span class="text">24 Saatte Kargoda</span></div></div></div></li>
                        <li class="swiper-slide swiper-slide-next"><div class="product-cr" id="product-527090"><a class="pr-img-link" href="https://www.kitapyurdu.com/kitap/medeniyet-dili-olarak-turkce-dilci-felsefe-ile-baslangic-ve-yontem-arayisi/527090.html"><img src="https://img.kitapyurdu.com/v1/getImage/fn:11587452/wi:120/wh:true" alt="Medeniyet Dili Olarak Türkçe &amp; Dilci Felsefe ile Başlangıç ve Yöntem Arayışı"></a><a class="name" href="https://www.kitapyurdu.com/kitap/medeniyet-dili-olarak-turkce-dilci-felsefe-ile-baslangic-ve-yontem-arayisi/527090.html" title="Medeniyet Dili Olarak Türkçe &amp; Dilci Felsefe ile Başlangıç ve Yöntem Arayışı"><span class=" line-clamp-2">Medeniyet Dili Olarak Türkçe &amp; Dilci Felsefe ile Başlangıç ve Yöntem Arayışı</span></a><div class="price"><div class="price-new "><span class="value"><span class="TL"></span> 42,35</span></div></div><div class="hover-menu-home"><a class="add-to-cart-home" onclick="addToCart(527090);" data-title="Sepete Ekle"><i class="fa fa-shopping-cart"></i></a><a onclick="showAjaxBox('https://www.kitapyurdu.com/index.php?route=product/product/page_image&amp;product_id=527090', true)" data-title="İç Sayfalar"><i class="fa fa-book"></i></a><a class="in-favorites-home" style="display:none;" onclick="removeFromFavorites(527090);" data-title="Favorilerinizde"><i class="fa fa-heart red"></i></a><a class="add-to-favorites-home" onclick="addToFavorites(527090);" data-title="Favorilerime Ekle"><i class="fa fa-heart"></i></a><a id="product-wish-list-remove-527090" onclick="removeFromWishList(527090);" data-title="Alışveriş Listemden Çıkar" style="color: #FF8000; display: none"><i class="fa fa-tag"></i></a><a id="product-wish-list-add-527090" onclick="addToWishList(527090);" data-title="Alışveriş Listeme Ekle" style="display: inline-block"><i class="fa fa-tag"></i></a></div><div class="notice-container"><div class="notice-home same-day purple"><i class="fa fa-plane"></i>&nbsp;<span class="text">24 Saatte Kargoda</span></div></div></div></li>
                        <li class="swiper-slide"><div class="product-cr" id="product-599995"><a class="pr-img-link" href="https://www.kitapyurdu.com/kitap/dosta-dogru-butun-siirleri-4/599995.html"><img src="https://img.kitapyurdu.com/v1/getImage/fn:11482689/wi:120/wh:true" alt="Dosta Doğru / Bütün Şiirleri 4"></a><a class="name" href="https://www.kitapyurdu.com/kitap/dosta-dogru-butun-siirleri-4/599995.html" title="Dosta Doğru / Bütün Şiirleri 4"><span class=" line-clamp-2">Dosta Doğru / Bütün Şiirleri 4</span></a><div class="price"><div class="price-new "><span class="value"><span class="TL"></span> 34,10</span></div></div><div class="hover-menu-home"><a class="add-to-cart-home" onclick="addToCart(599995);" data-title="Sepete Ekle"><i class="fa fa-shopping-cart"></i></a><a class="in-favorites-home" style="display:none;" onclick="removeFromFavorites(599995);" data-title="Favorilerinizde"><i class="fa fa-heart red"></i></a><a class="add-to-favorites-home" onclick="addToFavorites(599995);" data-title="Favorilerime Ekle"><i class="fa fa-heart"></i></a><a id="product-wish-list-remove-599995" onclick="removeFromWishList(599995);" data-title="Alışveriş Listemden Çıkar" style="color: #FF8000; display: none"><i class="fa fa-tag"></i></a><a id="product-wish-list-add-599995" onclick="addToWishList(599995);" data-title="Alışveriş Listeme Ekle" style="display: inline-block"><i class="fa fa-tag"></i></a></div><div class="notice-container"><div class="notice-home same-day purple"><i class="fa fa-plane"></i>&nbsp;<span class="text">24 Saatte Kargoda</span></div></div></div></li>
                        <li class="swiper-slide"><div class="product-cr" id="product-599993"><a class="pr-img-link" href="https://www.kitapyurdu.com/kitap/akil-karaya-vurdu-butun-siirleri-7/599993.html"><img src="https://img.kitapyurdu.com/v1/getImage/fn:11482685/wi:120/wh:true" alt="Akıl Karaya Vurdu / Bütün Şiirleri 7"></a><a class="name" href="https://www.kitapyurdu.com/kitap/akil-karaya-vurdu-butun-siirleri-7/599993.html" title="Akıl Karaya Vurdu / Bütün Şiirleri 7"><span class=" line-clamp-2">Akıl Karaya Vurdu / Bütün Şiirleri 7</span></a><div class="price"><div class="price-new "><span class="value"><span class="TL"></span> 33,00</span></div></div><div class="hover-menu-home"><a class="add-to-cart-home" onclick="addToCart(599993);" data-title="Sepete Ekle"><i class="fa fa-shopping-cart"></i></a><a class="in-favorites-home" style="display:none;" onclick="removeFromFavorites(599993);" data-title="Favorilerinizde"><i class="fa fa-heart red"></i></a><a class="add-to-favorites-home" onclick="addToFavorites(599993);" data-title="Favorilerime Ekle"><i class="fa fa-heart"></i></a><a id="product-wish-list-remove-599993" onclick="removeFromWishList(599993);" data-title="Alışveriş Listemden Çıkar" style="color: #FF8000; display: none"><i class="fa fa-tag"></i></a><a id="product-wish-list-add-599993" onclick="addToWishList(599993);" data-title="Alışveriş Listeme Ekle" style="display: inline-block"><i class="fa fa-tag"></i></a></div><div class="notice-container"><div class="notice-home same-day purple"><i class="fa fa-plane"></i>&nbsp;<span class="text">24 Saatte Kargoda</span></div></div></div></li>
                        <li class="swiper-slide"><div class="product-cr" id="product-629213"><a class="pr-img-link" href="https://www.kitapyurdu.com/kitap/bolseviklesme-surecinde-ermenigurcu-iliskileri-ve-turkiye-19171921/629213.html"><img src="https://img.kitapyurdu.com/v1/getImage/fn:11617870/wi:120/wh:true" alt="Bolşevikleşme Sürecinde Ermeni-Gürcü İlişkileri ve Türkiye 1917-1921"></a><a class="name" href="https://www.kitapyurdu.com/kitap/bolseviklesme-surecinde-ermenigurcu-iliskileri-ve-turkiye-19171921/629213.html" title="Bolşevikleşme Sürecinde Ermeni-Gürcü İlişkileri ve Türkiye 1917-1921"><span class=" line-clamp-2">Bolşevikleşme Sürecinde  Ermeni-Gürcü İlişkileri ve Türkiye  1917-1921</span></a><div class="price"><div class="price-new "><span class="value"><span class="TL"></span> 78,66</span></div></div><div class="hover-menu-home"><a class="add-to-cart-home" onclick="addToCart(629213);" data-title="Sepete Ekle"><i class="fa fa-shopping-cart"></i></a><a class="in-favorites-home" style="display:none;" onclick="removeFromFavorites(629213);" data-title="Favorilerinizde"><i class="fa fa-heart red"></i></a><a class="add-to-favorites-home" onclick="addToFavorites(629213);" data-title="Favorilerime Ekle"><i class="fa fa-heart"></i></a><a id="product-wish-list-remove-629213" onclick="removeFromWishList(629213);" data-title="Alışveriş Listemden Çıkar" style="color: #FF8000; display: none"><i class="fa fa-tag"></i></a><a id="product-wish-list-add-629213" onclick="addToWishList(629213);" data-title="Alışveriş Listeme Ekle" style="display: inline-block"><i class="fa fa-tag"></i></a></div><div class="notice-container"><div class="notice-home same-day purple"><i class="fa fa-plane"></i>&nbsp;<span class="text">24 Saatte Kargoda</span></div></div></div></li>
                        <li class="swiper-slide"><div class="product-cr" id="product-616000"><a class="pr-img-link" href="https://www.kitapyurdu.com/kitap/gok-turk-imparatorlugu/616000.html"><img src="https://img.kitapyurdu.com/v1/getImage/fn:11566474/wi:120/wh:true" alt="Gök Türk İmparatorluğu"></a><a class="name" href="https://www.kitapyurdu.com/kitap/gok-turk-imparatorlugu/616000.html" title="Gök Türk İmparatorluğu"><span class=" line-clamp-2">Gök Türk  İmparatorluğu</span></a><div class="price"><div class="price-new "><span class="value"><span class="TL"></span> 45,10</span></div></div><div class="hover-menu-home"><a class="add-to-cart-home" onclick="addToCart(616000);" data-title="Sepete Ekle"><i class="fa fa-shopping-cart"></i></a><a class="in-favorites-home" style="display:none;" onclick="removeFromFavorites(616000);" data-title="Favorilerinizde"><i class="fa fa-heart red"></i></a><a class="add-to-favorites-home" onclick="addToFavorites(616000);" data-title="Favorilerime Ekle"><i class="fa fa-heart"></i></a><a id="product-wish-list-remove-616000" onclick="removeFromWishList(616000);" data-title="Alışveriş Listemden Çıkar" style="color: #FF8000; display: none"><i class="fa fa-tag"></i></a><a id="product-wish-list-add-616000" onclick="addToWishList(616000);" data-title="Alışveriş Listeme Ekle" style="display: inline-block"><i class="fa fa-tag"></i></a></div><div class="notice-container"><div class="notice-home same-day purple"><i class="fa fa-plane"></i>&nbsp;<span class="text">24 Saatte Kargoda</span></div></div></div></li>
                        <li class="swiper-slide"><div class="product-cr" id="product-417362"><a class="pr-img-link" href="https://www.kitapyurdu.com/kitap/turkoloji-ders-notlari/417362.html"><img src="https://img.kitapyurdu.com/v1/getImage/fn:3202857/wi:120/wh:true" alt="Türkoloji Ders Notları"></a><a class="name" href="https://www.kitapyurdu.com/kitap/turkoloji-ders-notlari/417362.html" title="Türkoloji Ders Notları"><span class=" line-clamp-2">Türkoloji Ders Notları</span></a><div class="price"><div class="price-new "><span class="value"><span class="TL"></span> 28,60</span></div></div><div class="hover-menu-home"><a class="add-to-cart-home" onclick="addToCart(417362);" data-title="Sepete Ekle"><i class="fa fa-shopping-cart"></i></a><a onclick="showAjaxBox('https://www.kitapyurdu.com/index.php?route=product/product/page_image&amp;product_id=417362', true)" data-title="İç Sayfalar"><i class="fa fa-book"></i></a><a class="in-favorites-home" style="display:none;" onclick="removeFromFavorites(417362);" data-title="Favorilerinizde"><i class="fa fa-heart red"></i></a><a class="add-to-favorites-home" onclick="addToFavorites(417362);" data-title="Favorilerime Ekle"><i class="fa fa-heart"></i></a><a id="product-wish-list-remove-417362" onclick="removeFromWishList(417362);" data-title="Alışveriş Listemden Çıkar" style="color: #FF8000; display: none"><i class="fa fa-tag"></i></a><a id="product-wish-list-add-417362" onclick="addToWishList(417362);" data-title="Alışveriş Listeme Ekle" style="display: inline-block"><i class="fa fa-tag"></i></a></div><div class="notice-container"><div class="notice-home same-day purple"><i class="fa fa-plane"></i>&nbsp;<span class="text">24 Saatte Kargoda</span></div></div></div></li>
                        <li class="swiper-slide"><div class="product-cr" id="product-599996"><a class="pr-img-link" href="https://www.kitapyurdu.com/kitap/kan-yazisi-butun-siirleri-2/599996.html"><img src="https://img.kitapyurdu.com/v1/getImage/fn:11482691/wi:120/wh:true" alt="Kan Yazısı / Bütün Şiirleri 2"></a><a class="name" href="https://www.kitapyurdu.com/kitap/kan-yazisi-butun-siirleri-2/599996.html" title="Kan Yazısı / Bütün Şiirleri 2"><span class=" line-clamp-2">Kan Yazısı / Bütün Şiirleri 2</span></a><div class="price"><div class="price-new "><span class="value"><span class="TL"></span> 32,45</span></div></div><div class="hover-menu-home"><a class="add-to-cart-home" onclick="addToCart(599996);" data-title="Sepete Ekle"><i class="fa fa-shopping-cart"></i></a><a class="in-favorites-home" style="display:none;" onclick="removeFromFavorites(599996);" data-title="Favorilerinizde"><i class="fa fa-heart red"></i></a><a class="add-to-favorites-home" onclick="addToFavorites(599996);" data-title="Favorilerime Ekle"><i class="fa fa-heart"></i></a><a id="product-wish-list-remove-599996" onclick="removeFromWishList(599996);" data-title="Alışveriş Listemden Çıkar" style="color: #FF8000; display: none"><i class="fa fa-tag"></i></a><a id="product-wish-list-add-599996" onclick="addToWishList(599996);" data-title="Alışveriş Listeme Ekle" style="display: inline-block"><i class="fa fa-tag"></i></a></div><div class="notice-container"><div class="notice-home same-day purple"><i class="fa fa-plane"></i>&nbsp;<span class="text">24 Saatte Kargoda</span></div></div></div></li>
                        <li class="swiper-slide"><div class="product-cr" id="product-557759"><a class="pr-img-link" href="https://www.kitapyurdu.com/kitap/tarihte-ve-bugun-samanizm-materyaller-ve-arastirmalar/557759.html"><img src="https://img.kitapyurdu.com/v1/getImage/fn:11287427/wi:120/wh:true" alt="Tarihte ve Bugün Şamanizm &amp; Materyaller ve Araştırmalar"></a><a class="name" href="https://www.kitapyurdu.com/kitap/tarihte-ve-bugun-samanizm-materyaller-ve-arastirmalar/557759.html" title="Tarihte ve Bugün Şamanizm &amp; Materyaller ve Araştırmalar"><span class=" line-clamp-2">Tarihte ve Bugün Şamanizm &amp; Materyaller ve Araştırmalar</span></a><div class="price"><div class="price-new "><span class="value"><span class="TL"></span> 46,75</span></div></div><div class="hover-menu-home"><a class="add-to-cart-home" onclick="addToCart(557759);" data-title="Sepete Ekle"><i class="fa fa-shopping-cart"></i></a><a onclick="showAjaxBox('https://www.kitapyurdu.com/index.php?route=product/product/page_image&amp;product_id=557759', true)" data-title="İç Sayfalar"><i class="fa fa-book"></i></a><a class="in-favorites-home" style="display:none;" onclick="removeFromFavorites(557759);" data-title="Favorilerinizde"><i class="fa fa-heart red"></i></a><a class="add-to-favorites-home" onclick="addToFavorites(557759);" data-title="Favorilerime Ekle"><i class="fa fa-heart"></i></a><a id="product-wish-list-remove-557759" onclick="removeFromWishList(557759);" data-title="Alışveriş Listemden Çıkar" style="color: #FF8000; display: none"><i class="fa fa-tag"></i></a><a id="product-wish-list-add-557759" onclick="addToWishList(557759);" data-title="Alışveriş Listeme Ekle" style="display: inline-block"><i class="fa fa-tag"></i></a></div><div class="notice-container"><div class="notice-home same-day purple"><i class="fa fa-plane"></i>&nbsp;<span class="text">24 Saatte Kargoda</span></div></div></div></li>
                        <li class="swiper-slide"><div class="product-cr" id="product-621447"><a class="pr-img-link" href="https://www.kitapyurdu.com/kitap/medeniyet-dili-olarak-turkce-2-felsefi-antropoloji-yoluyla-dilde-medeniyet-kultur-tartismalari/621447.html"><img src="https://img.kitapyurdu.com/v1/getImage/fn:11583462/wi:120/wh:true" alt="Medeniyet Dili Olarak Türkçe - 2 Felsefi Antropoloji Yoluyla Dilde Medeniyet Kültür Tartışmaları"></a><a class="name" href="https://www.kitapyurdu.com/kitap/medeniyet-dili-olarak-turkce-2-felsefi-antropoloji-yoluyla-dilde-medeniyet-kultur-tartismalari/621447.html" title="Medeniyet Dili Olarak Türkçe - 2 Felsefi Antropoloji Yoluyla Dilde Medeniyet Kültür Tartışmaları"><span class=" line-clamp-2">Medeniyet Dili Olarak Türkçe - 2 Felsefi Antropoloji Yoluyla Dilde  Medeniyet Kültür Tartışmaları</span></a><div class="price"><div class="price-new "><span class="value"><span class="TL"></span> 52,26</span></div></div><div class="hover-menu-home"><a class="add-to-cart-home" onclick="addToCart(621447);" data-title="Sepete Ekle"><i class="fa fa-shopping-cart"></i></a><a onclick="showAjaxBox('https://www.kitapyurdu.com/index.php?route=product/product/page_image&amp;product_id=621447', true)" data-title="İç Sayfalar"><i class="fa fa-book"></i></a><a class="in-favorites-home" style="display:none;" onclick="removeFromFavorites(621447);" data-title="Favorilerinizde"><i class="fa fa-heart red"></i></a><a class="add-to-favorites-home" onclick="addToFavorites(621447);" data-title="Favorilerime Ekle"><i class="fa fa-heart"></i></a><a id="product-wish-list-remove-621447" onclick="removeFromWishList(621447);" data-title="Alışveriş Listemden Çıkar" style="color: #FF8000; display: none"><i class="fa fa-tag"></i></a><a id="product-wish-list-add-621447" onclick="addToWishList(621447);" data-title="Alışveriş Listeme Ekle" style="display: inline-block"><i class="fa fa-tag"></i></a></div><div class="notice-container"><div class="notice-home same-day purple"><i class="fa fa-plane"></i>&nbsp;<span class="text">24 Saatte Kargoda</span></div></div></div></li>
                        <li class="swiper-slide"><div class="product-cr" id="product-599994"><a class="pr-img-link" href="https://www.kitapyurdu.com/kitap/besinci-mevsim-butun-siirleri-5/599994.html"><img src="https://img.kitapyurdu.com/v1/getImage/fn:11482687/wi:120/wh:true" alt="Beşinci Mevsim / Bütün Şiirleri 5"></a><a class="name" href="https://www.kitapyurdu.com/kitap/besinci-mevsim-butun-siirleri-5/599994.html" title="Beşinci Mevsim / Bütün Şiirleri 5"><span class=" line-clamp-2">Beşinci Mevsim / Bütün Şiirleri 5</span></a><div class="price"><div class="price-new "><span class="value"><span class="TL"></span> 32,45</span></div></div><div class="hover-menu-home"><a class="add-to-cart-home" onclick="addToCart(599994);" data-title="Sepete Ekle"><i class="fa fa-shopping-cart"></i></a><a class="in-favorites-home" style="display:none;" onclick="removeFromFavorites(599994);" data-title="Favorilerinizde"><i class="fa fa-heart red"></i></a><a class="add-to-favorites-home" onclick="addToFavorites(599994);" data-title="Favorilerime Ekle"><i class="fa fa-heart"></i></a><a id="product-wish-list-remove-599994" onclick="removeFromWishList(599994);" data-title="Alışveriş Listemden Çıkar" style="color: #FF8000; display: none"><i class="fa fa-tag"></i></a><a id="product-wish-list-add-599994" onclick="addToWishList(599994);" data-title="Alışveriş Listeme Ekle" style="display: inline-block"><i class="fa fa-tag"></i></a></div><div class="notice-container"><div class="notice-home same-day purple"><i class="fa fa-plane"></i>&nbsp;<span class="text">24 Saatte Kargoda</span></div></div></div></li>
                        <li class="swiper-slide"><div class="product-cr" id="product-599998"><a class="pr-img-link" href="https://www.kitapyurdu.com/kitap/vur-emri-butun-siirleri-1/599998.html"><img src="https://img.kitapyurdu.com/v1/getImage/fn:11482748/wi:120/wh:true" alt="Vur Emri / Bütün Şiirleri 1"></a><a class="name" href="https://www.kitapyurdu.com/kitap/vur-emri-butun-siirleri-1/599998.html" title="Vur Emri / Bütün Şiirleri 1"><span class=" line-clamp-2">Vur Emri / Bütün Şiirleri 1</span></a><div class="price"><div class="price-new "><span class="value"><span class="TL"></span> 43,45</span></div></div><div class="hover-menu-home"><a class="add-to-cart-home" onclick="addToCart(599998);" data-title="Sepete Ekle"><i class="fa fa-shopping-cart"></i></a><a class="in-favorites-home" style="display:none;" onclick="removeFromFavorites(599998);" data-title="Favorilerinizde"><i class="fa fa-heart red"></i></a><a class="add-to-favorites-home" onclick="addToFavorites(599998);" data-title="Favorilerime Ekle"><i class="fa fa-heart"></i></a><a id="product-wish-list-remove-599998" onclick="removeFromWishList(599998);" data-title="Alışveriş Listemden Çıkar" style="color: #FF8000; display: none"><i class="fa fa-tag"></i></a><a id="product-wish-list-add-599998" onclick="addToWishList(599998);" data-title="Alışveriş Listeme Ekle" style="display: inline-block"><i class="fa fa-tag"></i></a></div><div class="notice-container"><div class="notice-home same-day purple"><i class="fa fa-plane"></i>&nbsp;<span class="text">24 Saatte Kargoda</span></div></div></div></li>
                        <li class="swiper-slide"><div class="product-cr" id="product-575669"><a class="pr-img-link" href="https://www.kitapyurdu.com/kitap/diksiyon-etkili-ve-guzel-konusma-sanati/575669.html"><img src="https://img.kitapyurdu.com/v1/getImage/fn:11383794/wi:120/wh:true" alt="Diksiyon &amp; Etkili ve Güzel Konuşma Sanatı"></a><a class="name" href="https://www.kitapyurdu.com/kitap/diksiyon-etkili-ve-guzel-konusma-sanati/575669.html" title="Diksiyon &amp; Etkili ve Güzel Konuşma Sanatı"><span class=" line-clamp-2">Diksiyon &amp; Etkili ve Güzel Konuşma Sanatı</span></a><div class="price"><div class="price-new "><span class="value"><span class="TL"></span> 38,50</span></div></div><div class="hover-menu-home"><a class="add-to-cart-home" onclick="addToCart(575669);" data-title="Sepete Ekle"><i class="fa fa-shopping-cart"></i></a><a onclick="showAjaxBox('https://www.kitapyurdu.com/index.php?route=product/product/page_image&amp;product_id=575669', true)" data-title="İç Sayfalar"><i class="fa fa-book"></i></a><a class="in-favorites-home" style="display:none;" onclick="removeFromFavorites(575669);" data-title="Favorilerinizde"><i class="fa fa-heart red"></i></a><a class="add-to-favorites-home" onclick="addToFavorites(575669);" data-title="Favorilerime Ekle"><i class="fa fa-heart"></i></a><a id="product-wish-list-remove-575669" onclick="removeFromWishList(575669);" data-title="Alışveriş Listemden Çıkar" style="color: #FF8000; display: none"><i class="fa fa-tag"></i></a><a id="product-wish-list-add-575669" onclick="addToWishList(575669);" data-title="Alışveriş Listeme Ekle" style="display: inline-block"><i class="fa fa-tag"></i></a></div><div class="notice-container"><div class="notice-home same-day purple"><i class="fa fa-plane"></i>&nbsp;<span class="text">24 Saatte Kargoda</span></div></div></div></li>
                        <li class="swiper-slide"><div class="product-cr" id="product-628358"><a class="pr-img-link" href="https://www.kitapyurdu.com/kitap/modern-cagda-savas-ve-diplomasi/628358.html"><img src="https://img.kitapyurdu.com/v1/getImage/fn:11613019/wi:120/wh:true" alt="Modern Çağ’da Savaş ve Diplomasi"></a><a class="name" href="https://www.kitapyurdu.com/kitap/modern-cagda-savas-ve-diplomasi/628358.html" title="Modern Çağ’da Savaş ve Diplomasi"><span class=" line-clamp-2">Modern Çağ’da Savaş ve Diplomasi</span></a><div class="price"><div class="price-new "><span class="value"><span class="TL"></span> 85,26</span></div></div><div class="hover-menu-home"><a class="add-to-cart-home" onclick="addToCart(628358);" data-title="Sepete Ekle"><i class="fa fa-shopping-cart"></i></a><a class="in-favorites-home" style="display:none;" onclick="removeFromFavorites(628358);" data-title="Favorilerinizde"><i class="fa fa-heart red"></i></a><a class="add-to-favorites-home" onclick="addToFavorites(628358);" data-title="Favorilerime Ekle"><i class="fa fa-heart"></i></a><a id="product-wish-list-remove-628358" onclick="removeFromWishList(628358);" data-title="Alışveriş Listemden Çıkar" style="color: #FF8000; display: none"><i class="fa fa-tag"></i></a><a id="product-wish-list-add-628358" onclick="addToWishList(628358);" data-title="Alışveriş Listeme Ekle" style="display: inline-block"><i class="fa fa-tag"></i></a></div><div class="notice-container"></div></div></li>
                        <li class="swiper-slide"><div class="product-cr" id="product-517746"><a class="pr-img-link" href="https://www.kitapyurdu.com/kitap/gonye-ve-hilal-jon-turkler-ve-italyan-masonlugu/517746.html"><img src="https://img.kitapyurdu.com/v1/getImage/fn:9993151/wi:120/wh:true" alt="Gönye ve Hilal &amp; Jön Türkler ve İtalyan Masonluğu"></a><a class="name" href="https://www.kitapyurdu.com/kitap/gonye-ve-hilal-jon-turkler-ve-italyan-masonlugu/517746.html" title="Gönye ve Hilal &amp; Jön Türkler ve İtalyan Masonluğu"><span class=" line-clamp-2">Gönye ve Hilal &amp; Jön Türkler ve İtalyan Masonluğu</span></a><div class="price"><div class="price-new "><span class="value"><span class="TL"></span> 27,50</span></div></div><div class="hover-menu-home"><a class="add-to-cart-home" onclick="addToCart(517746);" data-title="Sepete Ekle"><i class="fa fa-shopping-cart"></i></a><a onclick="showAjaxBox('https://www.kitapyurdu.com/index.php?route=product/product/page_image&amp;product_id=517746', true)" data-title="İç Sayfalar"><i class="fa fa-book"></i></a><a class="in-favorites-home" style="display:none;" onclick="removeFromFavorites(517746);" data-title="Favorilerinizde"><i class="fa fa-heart red"></i></a><a class="add-to-favorites-home" onclick="addToFavorites(517746);" data-title="Favorilerime Ekle"><i class="fa fa-heart"></i></a><a id="product-wish-list-remove-517746" onclick="removeFromWishList(517746);" data-title="Alışveriş Listemden Çıkar" style="color: #FF8000; display: none"><i class="fa fa-tag"></i></a><a id="product-wish-list-add-517746" onclick="addToWishList(517746);" data-title="Alışveriş Listeme Ekle" style="display: inline-block"><i class="fa fa-tag"></i></a></div><div class="notice-container"><div class="notice-home same-day purple"><i class="fa fa-plane"></i>&nbsp;<span class="text">24 Saatte Kargoda</span></div></div></div></li>
                        <li class="swiper-slide"><div class="product-cr" id="product-512289"><a class="pr-img-link" href="https://www.kitapyurdu.com/kitap/eli-cohen-casus-/512289.html"><img src="https://img.kitapyurdu.com/v1/getImage/fn:9642936/wi:120/wh:true" alt="Eli Cohen Casus"></a><a class="name" href="https://www.kitapyurdu.com/kitap/eli-cohen-casus-/512289.html" title="Eli Cohen Casus"><span class=" line-clamp-2">Eli Cohen Casus </span></a><div class="price"><div class="price-new "><span class="value"><span class="TL"></span> 44,00</span></div></div><div class="hover-menu-home"><a class="add-to-cart-home" onclick="addToCart(512289);" data-title="Sepete Ekle"><i class="fa fa-shopping-cart"></i></a><a onclick="showAjaxBox('https://www.kitapyurdu.com/index.php?route=product/product/page_image&amp;product_id=512289', true)" data-title="İç Sayfalar"><i class="fa fa-book"></i></a><a class="in-favorites-home" style="display:none;" onclick="removeFromFavorites(512289);" data-title="Favorilerinizde"><i class="fa fa-heart red"></i></a><a class="add-to-favorites-home" onclick="addToFavorites(512289);" data-title="Favorilerime Ekle"><i class="fa fa-heart"></i></a><a id="product-wish-list-remove-512289" onclick="removeFromWishList(512289);" data-title="Alışveriş Listemden Çıkar" style="color: #FF8000; display: none"><i class="fa fa-tag"></i></a><a id="product-wish-list-add-512289" onclick="addToWishList(512289);" data-title="Alışveriş Listeme Ekle" style="display: inline-block"><i class="fa fa-tag"></i></a></div><div class="notice-container"><div class="notice-home same-day purple"><i class="fa fa-plane"></i>&nbsp;<span class="text">24 Saatte Kargoda</span></div></div></div></li>
                        <li class="swiper-slide"><div class="product-cr" id="product-556269"><a class="pr-img-link" href="https://www.kitapyurdu.com/kitap/universiteler-icin-turkce-dil-bilgisi/556269.html"><img src="https://img.kitapyurdu.com/v1/getImage/fn:11280294/wi:120/wh:true" alt="Üniversiteler İçin Türkçe Dil Bilgisi"></a><a class="name" href="https://www.kitapyurdu.com/kitap/universiteler-icin-turkce-dil-bilgisi/556269.html" title="Üniversiteler İçin Türkçe Dil Bilgisi"><span class=" line-clamp-2">Üniversiteler İçin Türkçe Dil Bilgisi</span></a><div class="price"><div class="price-new "><span class="value"><span class="TL"></span> 79,76</span></div></div><div class="hover-menu-home"><a class="add-to-cart-home" onclick="addToCart(556269);" data-title="Sepete Ekle"><i class="fa fa-shopping-cart"></i></a><a class="in-favorites-home" style="display:none;" onclick="removeFromFavorites(556269);" data-title="Favorilerinizde"><i class="fa fa-heart red"></i></a><a class="add-to-favorites-home" onclick="addToFavorites(556269);" data-title="Favorilerime Ekle"><i class="fa fa-heart"></i></a><a id="product-wish-list-remove-556269" onclick="removeFromWishList(556269);" data-title="Alışveriş Listemden Çıkar" style="color: #FF8000; display: none"><i class="fa fa-tag"></i></a><a id="product-wish-list-add-556269" onclick="addToWishList(556269);" data-title="Alışveriş Listeme Ekle" style="display: inline-block"><i class="fa fa-tag"></i></a></div><div class="notice-container"><div class="notice-home same-day purple"><i class="fa fa-plane"></i>&nbsp;<span class="text">24 Saatte Kargoda</span></div></div></div></li>
                        <li class="swiper-slide"><div class="product-cr" id="product-514032"><a class="pr-img-link" href="https://www.kitapyurdu.com/kitap/tanri-ile-kavga-18yy-fransiz-aydinlanmasinda-dhollbach-sistemi/514032.html"><img src="https://img.kitapyurdu.com/v1/getImage/fn:9748310/wi:120/wh:true" alt="Tanrı ile Kavga &amp; 18.yy Fransız Aydınlanmasında D’Hollbach Sistemi"></a><a class="name" href="https://www.kitapyurdu.com/kitap/tanri-ile-kavga-18yy-fransiz-aydinlanmasinda-dhollbach-sistemi/514032.html" title="Tanrı ile Kavga &amp; 18.yy Fransız Aydınlanmasında D’Hollbach Sistemi"><span class=" line-clamp-2">Tanrı ile Kavga &amp; 18.yy Fransız Aydınlanmasında D’Hollbach Sistemi</span></a><div class="price"><div class="price-new "><span class="value"><span class="TL"></span> 38,50</span></div></div><div class="hover-menu-home"><a class="add-to-cart-home" onclick="addToCart(514032);" data-title="Sepete Ekle"><i class="fa fa-shopping-cart"></i></a><a onclick="showAjaxBox('https://www.kitapyurdu.com/index.php?route=product/product/page_image&amp;product_id=514032', true)" data-title="İç Sayfalar"><i class="fa fa-book"></i></a><a class="in-favorites-home" style="display:none;" onclick="removeFromFavorites(514032);" data-title="Favorilerinizde"><i class="fa fa-heart red"></i></a><a class="add-to-favorites-home" onclick="addToFavorites(514032);" data-title="Favorilerime Ekle"><i class="fa fa-heart"></i></a><a id="product-wish-list-remove-514032" onclick="removeFromWishList(514032);" data-title="Alışveriş Listemden Çıkar" style="color: #FF8000; display: none"><i class="fa fa-tag"></i></a><a id="product-wish-list-add-514032" onclick="addToWishList(514032);" data-title="Alışveriş Listeme Ekle" style="display: inline-block"><i class="fa fa-tag"></i></a></div><div class="notice-container"><div class="notice-home same-day purple"><i class="fa fa-plane"></i>&nbsp;<span class="text">24 Saatte Kargoda</span></div></div></div></li>
                        <li class="swiper-slide"><div class="product-cr" id="product-567345"><a class="pr-img-link" href="https://www.kitapyurdu.com/kitap/osmanli-devletinin-diplomasi-tarihi-makaleler-1/567345.html"><img src="https://img.kitapyurdu.com/v1/getImage/fn:11336341/wi:120/wh:true" alt="Osmanlı Devleti’nin Diplomasi Tarihi / Makaleler 1"></a><a class="name" href="https://www.kitapyurdu.com/kitap/osmanli-devletinin-diplomasi-tarihi-makaleler-1/567345.html" title="Osmanlı Devleti’nin Diplomasi Tarihi / Makaleler 1"><span class=" line-clamp-2">Osmanlı Devleti’nin  Diplomasi Tarihi / Makaleler 1</span></a><div class="price"><div class="price-new "><span class="value"><span class="TL"></span> 66,01</span></div></div><div class="hover-menu-home"><a class="add-to-cart-home" onclick="addToCart(567345);" data-title="Sepete Ekle"><i class="fa fa-shopping-cart"></i></a><a class="in-favorites-home" style="display:none;" onclick="removeFromFavorites(567345);" data-title="Favorilerinizde"><i class="fa fa-heart red"></i></a><a class="add-to-favorites-home" onclick="addToFavorites(567345);" data-title="Favorilerime Ekle"><i class="fa fa-heart"></i></a><a id="product-wish-list-remove-567345" onclick="removeFromWishList(567345);" data-title="Alışveriş Listemden Çıkar" style="color: #FF8000; display: none"><i class="fa fa-tag"></i></a><a id="product-wish-list-add-567345" onclick="addToWishList(567345);" data-title="Alışveriş Listeme Ekle" style="display: inline-block"><i class="fa fa-tag"></i></a></div><div class="notice-container"><div class="notice-home same-day purple"><i class="fa fa-plane"></i>&nbsp;<span class="text">24 Saatte Kargoda</span></div></div></div></li>
                        <li class="swiper-slide"><div class="product-cr" id="product-455312"><a class="pr-img-link" href="https://www.kitapyurdu.com/kitap/bilinmeyen-yonleriyle-cemil-meric/455312.html"><img src="https://img.kitapyurdu.com/v1/getImage/fn:5660115/wi:120/wh:true" alt="Bilinmeyen Yönleriyle Cemil Meriç"></a><a class="name" href="https://www.kitapyurdu.com/kitap/bilinmeyen-yonleriyle-cemil-meric/455312.html" title="Bilinmeyen Yönleriyle Cemil Meriç"><span class=" line-clamp-2">Bilinmeyen Yönleriyle Cemil Meriç</span></a><div class="price"><div class="price-new "><span class="value"><span class="TL"></span> 71,51</span></div></div><div class="hover-menu-home"><a class="add-to-cart-home" onclick="addToCart(455312);" data-title="Sepete Ekle"><i class="fa fa-shopping-cart"></i></a><a class="in-favorites-home" style="display:none;" onclick="removeFromFavorites(455312);" data-title="Favorilerinizde"><i class="fa fa-heart red"></i></a><a class="add-to-favorites-home" onclick="addToFavorites(455312);" data-title="Favorilerime Ekle"><i class="fa fa-heart"></i></a><a id="product-wish-list-remove-455312" onclick="removeFromWishList(455312);" data-title="Alışveriş Listemden Çıkar" style="color: #FF8000; display: none"><i class="fa fa-tag"></i></a><a id="product-wish-list-add-455312" onclick="addToWishList(455312);" data-title="Alışveriş Listeme Ekle" style="display: inline-block"><i class="fa fa-tag"></i></a></div><div class="notice-container"><div class="notice-home same-day purple"><i class="fa fa-plane"></i>&nbsp;<span class="text">24 Saatte Kargoda</span></div></div></div></li>
                    </ul>
                <div class="swiper-scrollbar" style="opacity: 0; transition-duration: 400ms;"><div class="swiper-scrollbar-drag" style="transform: translate3d(0px, 0px, 0px); width: 150.136px;"></div></div>
            <span class="swiper-notification" aria-live="assertive" aria-atomic="true"></span></div>
            </div>
                    <div class="box-heading featured-publisher-heading next-week">
                        <div class="ribbon-container">
                            <div class="ribbon-text">Gelecek Haftanın Yayınevi</div>
                        </div>
            
                            <a class="pub-image-cr" href="https://www.kitapyurdu.com/yayinevi/celik-yayinevi/485.html">
                        <img class="pub-image" src="https://img.kitapyurdu.com/v1/getImage/fn:3877269/wi:100/wh:c8c1716f2" alt="ÇELİK YAYINEVİ" title="ÇELİK YAYINEVİ" width="100" height="100">
                    </a>
                    
                    <div class="pub-name line-clamp-3">
                        <span>ÇELİK YAYINEVİ</span>
                    </div>
            
                            <div class="featured-publisher-discount">%45'e<br>varan indirim</div>
                    
                    <span class="tooltip-discount-date" data-title="21 Kasım - 28 Kasım tarihleri arasında geçerlidir."><i class="common-sprite info"></i></span>
            
                    <a class="btn-prepare-cart" href="https://www.kitapyurdu.com/yayinevi/celik-yayinevi/485.html"> <span>Sepetinizi Hazırlayın</span> <i class="common-sprite red-next"></i> </a>
            
                </div>
            </div>

        </div>
    </div>
</template>