<template>
    <div>
        <div class="home js-ajax" style=" max-width:1200px;"><div class="box gray no-padding has-subtitle" id="js-game_product_carousel_0" style="margin-left: 450px;">
            <div class="box-heading padding">
                <div class="ribbon-container">
                    <div class="ribbon-text">Oyundan Daha Fazlası</div>
                </div>
                <div class="heading-nav-horizontal">
                    <a class="view-all" href="https://www.kitapyurdu.com/index.php?route=product/best_sellers&amp;sort=purchased&amp;order=DESC&amp;list_id=758&amp;filter_in_stock=1" data-title="Çocuk Zeka Oyunları" style="margin-left:450px;">Tümünü Göster</a>
                    <div class="heading-nav-arrows"><a class="common-sprite prev swiper-button-disabled" tabindex="0" role="button" aria-label="Previous slide" aria-disabled="true"></a><a class="common-sprite next" tabindex="0" role="button" aria-label="Next slide" aria-disabled="false"></a></div>
                </div>
        
                <div class="js-heading-links">
                    <a class="sub-title-1143 selected">Çocuk Zeka Oyunları</a>
                    <a class="sub-title-1145">Çocuklar İçin Puzzle</a>
                    <a class="sub-title-1146">Yetişkin Zeka Oyunları</a>
                    <a class="sub-title-1144">Yetişkinler İçin Puzzle</a>
                   
                </div>
            </div>
        
            <div class="box-content product-grid-wr"><div class="swiper-container swiper-container-initialized swiper-container-horizontal" style="cursor: grab;">
            <ul class="product-grid swiper-wrapper" style="display: flex; width: 100%; transition-duration: 0ms; transform: translate3d(2px, 0px, 0px);">
                    <li class="swiper-slide swiper-slide-active"><div class="product-cr" id="product-489947"><a class="pr-img-link" href="https://www.kitapyurdu.com/oyuncak/montessori-ahsap-zeka-oyunlari-wsymbol-18-xxl/489947.html"><img src="https://img.kitapyurdu.com/v1/getImage/fn:9552086/wi:120/wh:true" alt="Montessori Ahşap Zeka Oyunları / w-Symbol 18 (XXL)"></a><a class="name" href="https://www.kitapyurdu.com/oyuncak/montessori-ahsap-zeka-oyunlari-wsymbol-18-xxl/489947.html" title="Montessori Ahşap Zeka Oyunları / w-Symbol 18 (XXL)"><span class=" line-clamp-2">Montessori Ahşap Zeka Oyunları / w-Symbol 18 (XXL)</span></a><div class="price"><div class="price-new "><span class="value"><span class="TL"></span> 87,75</span></div></div><div class="hover-menu-home"><a class="add-to-cart-home" onclick="addToCart(489947);" data-title="Sepete Ekle"><i class="fa fa-shopping-cart"></i></a><a class="in-favorites-home" style="display:none;" onclick="removeFromFavorites(489947);" data-title="Favorilerinizde"><i class="fa fa-heart red"></i></a><a class="add-to-favorites-home" onclick="addToFavorites(489947);" data-title="Favorilerime Ekle"><i class="fa fa-heart"></i></a><a id="product-wish-list-remove-489947" onclick="removeFromWishList(489947);" data-title="Alışveriş Listemden Çıkar" style="color: #FF8000; display: none"><i class="fa fa-tag"></i></a><a id="product-wish-list-add-489947" onclick="addToWishList(489947);" data-title="Alışveriş Listeme Ekle" style="display: inline-block"><i class="fa fa-tag"></i></a></div><div class="notice-container"><div class="notice-home same-day purple"><i class="fa fa-plane"></i>&nbsp;<span class="text">24 Saatte Kargoda</span></div></div></div></li>
                    <li class="swiper-slide swiper-slide-next"><div class="product-cr" id="product-467427"><a class="pr-img-link" href="https://www.kitapyurdu.com/oyuncak/montessori-ahsap-zeka-oyunlari-wtetrisk-14/467427.html"><img src="https://img.kitapyurdu.com/v1/getImage/fn:8092781/wi:120/wh:true" alt="Montessori Ahşap Zeka Oyunları / w-Tetrisk 14"></a><a class="name" href="https://www.kitapyurdu.com/oyuncak/montessori-ahsap-zeka-oyunlari-wtetrisk-14/467427.html" title="Montessori Ahşap Zeka Oyunları / w-Tetrisk 14"><span class=" line-clamp-2">Montessori Ahşap Zeka Oyunları / w-Tetrisk 14</span></a><div class="price"><div class="price-new "><span class="value"><span class="TL"></span> 60,01</span></div></div><div class="hover-menu-home"><a class="add-to-cart-home" onclick="addToCart(467427);" data-title="Sepete Ekle"><i class="fa fa-shopping-cart"></i></a><a class="in-favorites-home" style="display:none;" onclick="removeFromFavorites(467427);" data-title="Favorilerinizde"><i class="fa fa-heart red"></i></a><a class="add-to-favorites-home" onclick="addToFavorites(467427);" data-title="Favorilerime Ekle"><i class="fa fa-heart"></i></a><a id="product-wish-list-remove-467427" onclick="removeFromWishList(467427);" data-title="Alışveriş Listemden Çıkar" style="color: #FF8000; display: none"><i class="fa fa-tag"></i></a><a id="product-wish-list-add-467427" onclick="addToWishList(467427);" data-title="Alışveriş Listeme Ekle" style="display: inline-block"><i class="fa fa-tag"></i></a></div><div class="notice-container"><div class="notice-home same-day purple"><i class="fa fa-plane"></i>&nbsp;<span class="text">24 Saatte Kargoda</span></div></div></div></li>
                    <li class="swiper-slide"><div class="product-cr" id="product-467424"><a class="pr-img-link" href="https://www.kitapyurdu.com/oyuncak/montessori-ahsap-zeka-oyunlari-wsquare-14/467424.html"><img src="https://img.kitapyurdu.com/v1/getImage/fn:8092685/wi:120/wh:true" alt="Montessori Ahşap Zeka Oyunları / w-Square 14"></a><a class="name" href="https://www.kitapyurdu.com/oyuncak/montessori-ahsap-zeka-oyunlari-wsquare-14/467424.html" title="Montessori Ahşap Zeka Oyunları / w-Square 14"><span class=" line-clamp-2">Montessori Ahşap Zeka Oyunları / w-Square 14</span></a><div class="price"><div class="price-new "><span class="value"><span class="TL"></span> 90,00</span></div></div><div class="hover-menu-home"><a class="add-to-cart-home" onclick="addToCart(467424);" data-title="Sepete Ekle"><i class="fa fa-shopping-cart"></i></a><a class="in-favorites-home" style="display:none;" onclick="removeFromFavorites(467424);" data-title="Favorilerinizde"><i class="fa fa-heart red"></i></a><a class="add-to-favorites-home" onclick="addToFavorites(467424);" data-title="Favorilerime Ekle"><i class="fa fa-heart"></i></a><a id="product-wish-list-remove-467424" onclick="removeFromWishList(467424);" data-title="Alışveriş Listemden Çıkar" style="color: #FF8000; display: none"><i class="fa fa-tag"></i></a><a id="product-wish-list-add-467424" onclick="addToWishList(467424);" data-title="Alışveriş Listeme Ekle" style="display: inline-block"><i class="fa fa-tag"></i></a></div><div class="notice-container"><div class="notice-home same-day purple"><i class="fa fa-plane"></i>&nbsp;<span class="text">24 Saatte Kargoda</span></div></div></div></li>
                    <li class="swiper-slide"><div class="product-cr" id="product-401302"><a class="pr-img-link" href="https://www.kitapyurdu.com/kitap/ilk-50-sozcuk-egitici-flash-card/401302.html"><img src="https://img.kitapyurdu.com/v1/getImage/fn:11446756/wi:120/wh:true" alt="İlk 50 Sözcük (Eğitici Flash Card)"></a><a class="name" href="https://www.kitapyurdu.com/kitap/ilk-50-sozcuk-egitici-flash-card/401302.html" title="İlk 50 Sözcük (Eğitici Flash Card)"><span class=" line-clamp-2">İlk 50 Sözcük (Eğitici Flash Card)</span></a><div class="price"><div class="price-new "><span class="value"><span class="TL"></span> 33,10</span></div></div><div class="hover-menu-home"><a class="add-to-cart-home" onclick="addToCart(401302);" data-title="Sepete Ekle"><i class="fa fa-shopping-cart"></i></a><a class="in-favorites-home" style="display:none;" onclick="removeFromFavorites(401302);" data-title="Favorilerinizde"><i class="fa fa-heart red"></i></a><a class="add-to-favorites-home" onclick="addToFavorites(401302);" data-title="Favorilerime Ekle"><i class="fa fa-heart"></i></a><a id="product-wish-list-remove-401302" onclick="removeFromWishList(401302);" data-title="Alışveriş Listemden Çıkar" style="color: #FF8000; display: none"><i class="fa fa-tag"></i></a><a id="product-wish-list-add-401302" onclick="addToWishList(401302);" data-title="Alışveriş Listeme Ekle" style="display: inline-block"><i class="fa fa-tag"></i></a></div><div class="notice-container"><div class="notice-home same-day purple"><i class="fa fa-plane"></i>&nbsp;<span class="text">24 Saatte Kargoda</span></div></div></div></li>
                    <li class="swiper-slide"><div class="product-cr" id="product-369977"><a class="pr-img-link" href="https://www.kitapyurdu.com/oyuncak/scrabble-original-turkcey9611/369977.html"><img src="https://img.kitapyurdu.com/v1/getImage/fn:10836846/wi:120/wh:true" alt="Scrabble Original Türkçe(Y9611)"></a><a class="name" href="https://www.kitapyurdu.com/oyuncak/scrabble-original-turkcey9611/369977.html" title="Scrabble Original Türkçe(Y9611)"><span class=" line-clamp-2">Scrabble Original Türkçe(Y9611)</span></a><div class="price"><div class="price-new "><span class="value"><span class="TL"></span> 198,72</span></div></div><div class="hover-menu-home"><a class="add-to-cart-home" onclick="addToCart(369977);" data-title="Sepete Ekle"><i class="fa fa-shopping-cart"></i></a><a class="in-favorites-home" style="display:none;" onclick="removeFromFavorites(369977);" data-title="Favorilerinizde"><i class="fa fa-heart red"></i></a><a class="add-to-favorites-home" onclick="addToFavorites(369977);" data-title="Favorilerime Ekle"><i class="fa fa-heart"></i></a><a id="product-wish-list-remove-369977" onclick="removeFromWishList(369977);" data-title="Alışveriş Listemden Çıkar" style="color: #FF8000; display: none"><i class="fa fa-tag"></i></a><a id="product-wish-list-add-369977" onclick="addToWishList(369977);" data-title="Alışveriş Listeme Ekle" style="display: inline-block"><i class="fa fa-tag"></i></a></div><div class="notice-container"><div class="notice-home free-shipping-same-day purple"><i class="fa fa-plane"></i>&nbsp;<div class="text">Kargo Bedava<br>24 Saatte Kargoda</div></div></div></div></li>
                    
                </ul>
            <div class="swiper-scrollbar" style="opacity: 0; transition-duration: 400ms;"><div class="swiper-scrollbar-drag" style="transform: translate3d(0px, 0px, 0px); width: 493.215px;"></div></div>
        <span class="swiper-notification" aria-live="assertive" aria-atomic="true"></span></div>
        </div>
        </div>
        
        
        </div>
    </div>
</template>